We are going to modify the generated views slightly to include functionality which enables to upload a featured image.

In Point of Interest's listing, display only the hotel's name in the table. Checkout the http://grails3-plugins.github.io/fields/snapshot/ref/Tags/table.html[Fields Plugin f:table] documentation.

[source, groovy]
./grails-app/views/pointOfInterest/index.gsp
----
include::{sourceDir}/grails-app/views/pointOfInterest/index.gsp[indent=0,lines="21"]
----

Edit and create form will not allow users to set featured image's url

[source, groovy]
./grails-app/views/pointOfInterest/create.gsp
----
include::{sourceDir}/grails-app/views/pointOfInterest/create.gsp[indent=0,lines="30"]
----

[source, groovy]
./grails-app/views/pointOfInterest/edit.gsp
----
include::{sourceDir}/grails-app/views/pointOfInterest/edit.gsp[indent=0,lines="32"]
----

Instead we add a button which takes the user to a featured image edit page.

[source, groovy]
./grails-app/views/pointOfInterest/show.gsp
----
include::{sourceDir}/grails-app/views/pointOfInterest/show.gsp[indent=0,lines="28"]
----

`editFeaturedImage` Controller's action is identical to edit action:

[source, groovy]
./grails-app/controllers/demo/PointOfInterestController.groovy
----
include::{sourceDir}/grails-app/controllers/demo/PointOfInterestController.groovy[indent=0, tag=editFeaturedImage]
----

`editFeaturedImage` GSP is identical to `edit` GSP but it uses an `g:uploadForm` instead of a `g:form`

[source, groovy]
./grails-app/views/pointOfInterest/editFeaturedImage.gsp
----
include::{sourceDir}/grails-app/views/pointOfInterest/editFeaturedImage.gsp[indent=0,lines="29..36"]
----
